"""Prompt and orchestration history limits for the Streamlit RP app (Issue #174).

Values are re-exported from app.py — import from `app` in product code.
"""

PROMPT_DIALOGUE_HISTORY_LIMIT = 6
PROMPT_STRUCTURED_MOVE_LIMIT = 4
DIRECTOR_SPOTLIGHT_HISTORY_LIMIT = 6
ORCHESTRATION_SPOTLIGHT_HISTORY_LIMIT = 12
ORCHESTRATION_STRUCTURED_MOVE_HISTORY_LIMIT = 8
ORCHESTRATION_DIRECTOR_DECISION_HISTORY_LIMIT = 8
ORCHESTRATION_ENVIRONMENT_HISTORY_LIMIT = 8
ORCHESTRATION_TENSION_HISTORY_LIMIT = 8
