"""Public façade for a single bot character turn — sequences attempt then render phases."""

from typing import Any

from turn_runner_character_attempt import (
    DEFAULT_MAX_CHARACTER_ATTEMPTS,
    _CHARACTER_MOVE_PARSE_JSON_DISCIPLINE_NOTE,
    run_character_attempt_phase,
)
from turn_runner_character_render import (
    _narrate_move_for_character_turn,
    execute_character_turn_render_phase,
)


async def execute_character_turn(
    *,
    st_module: Any,
    agent: Any,
    narrator: Any,
    next_actor: str,
    char_names: list[str],
    decision: dict[str, Any],
    trigger_text: str,
    user_name: str,
    cancellation_token: Any,
    round_number: int,
    turn_number: int,
    orchestration_state: dict[str, Any],
    actors_failed_this_round: list[str],
    state_manager: Any,
    build_character_turn_prompt_fn,
    parse_character_move_fn,
    get_continuity_manager_fn,
    is_audit_enabled_fn,
    is_llm_audit_enabled_fn,
    get_audit_logger_fn,
    get_audit_context_fn,
    get_scene_audit_logging_kwargs_fn,
    get_character_scene_audit_context_fn,
    validate_bot_response_fn,
    get_model_client_fn,
    assess_presence_violation_semantics_fn,
    should_override_presence_rejection_fn,
    build_recent_scene_context_fn,
    render_character_move_fn,
    fallback_render_move_fn,
    assess_narrator_render_semantics_fn,
    log_turn_failure_fn,
    get_character_display_name_fn,
    sync_orchestration_state_from_continuity_fn,
    effective_user_trigger: str = "",
    max_character_attempts: int = DEFAULT_MAX_CHARACTER_ATTEMPTS,
) -> dict[str, Any] | None:
    effective_user_trigger = (effective_user_trigger or trigger_text or "").strip()
    task_prompt, character_summary_block_audit = build_character_turn_prompt_fn(
        next_actor,
        user_name,
        trigger_text,
        decision,
    )
    outcome = await run_character_attempt_phase(
        st_module=st_module,
        agent=agent,
        next_actor=next_actor,
        char_names=char_names,
        decision=decision,
        trigger_text=trigger_text,
        user_name=user_name,
        cancellation_token=cancellation_token,
        round_number=round_number,
        turn_number=turn_number,
        orchestration_state=orchestration_state,
        actors_failed_this_round=actors_failed_this_round,
        state_manager=state_manager,
        task_prompt=task_prompt,
        character_summary_block_audit=character_summary_block_audit,
        parse_character_move_fn=parse_character_move_fn,
        get_continuity_manager_fn=get_continuity_manager_fn,
        is_audit_enabled_fn=is_audit_enabled_fn,
        is_llm_audit_enabled_fn=is_llm_audit_enabled_fn,
        get_audit_logger_fn=get_audit_logger_fn,
        get_audit_context_fn=get_audit_context_fn,
        get_scene_audit_logging_kwargs_fn=get_scene_audit_logging_kwargs_fn,
        get_character_scene_audit_context_fn=get_character_scene_audit_context_fn,
        validate_bot_response_fn=validate_bot_response_fn,
        get_model_client_fn=get_model_client_fn,
        assess_presence_violation_semantics_fn=assess_presence_violation_semantics_fn,
        should_override_presence_rejection_fn=should_override_presence_rejection_fn,
        log_turn_failure_fn=log_turn_failure_fn,
        sync_orchestration_state_from_continuity_fn=sync_orchestration_state_from_continuity_fn,
        effective_user_trigger=effective_user_trigger,
        max_character_attempts=max_character_attempts,
    )
    if outcome is None:
        return None
    return await execute_character_turn_render_phase(
        st_module=st_module,
        narrator=narrator,
        next_actor=next_actor,
        char_names=char_names,
        decision=decision,
        orchestration_state=orchestration_state,
        actors_failed_this_round=actors_failed_this_round,
        cancellation_token=cancellation_token,
        round_number=round_number,
        turn_number=turn_number,
        build_recent_scene_context_fn=build_recent_scene_context_fn,
        render_character_move_fn=render_character_move_fn,
        fallback_render_move_fn=fallback_render_move_fn,
        assess_narrator_render_semantics_fn=assess_narrator_render_semantics_fn,
        log_turn_failure_fn=log_turn_failure_fn,
        get_character_display_name_fn=get_character_display_name_fn,
        get_model_client_fn=get_model_client_fn,
        sync_orchestration_state_from_continuity_fn=sync_orchestration_state_from_continuity_fn,
        is_audit_enabled_fn=is_audit_enabled_fn,
        is_llm_audit_enabled_fn=is_llm_audit_enabled_fn,
        effective_user_trigger=effective_user_trigger,
        outcome=outcome,
    )
